### ISSUE TITLE
`link` without arguments produces a TypeError

### ISSUE THREAD

**Issue by williamjacksn** [netlify/cli#675]
**- Do you want to request a _feature_ or report a _bug_?**

Report a bug.

**- What is the current behavior?**

Beginning with 2.26.0, running `netlify link` with no arguments produces an error instead of asking questions.

```sh
> netlify link
TypeError: context.log is not a function
    at linkPrompts (~/.config/yarn/global/node_modules/netlify-cli/src/utils/link/link-by-prompt.js:32:11)
    at async LinkCommand.run (~/.config/yarn/global/node_modules/netlify-cli/src/commands/link.js:106:16)
    at async LinkCommand._run (~/.config/yarn/global/node_modules/@oclif/command/lib/command.js:44:20)
    at async Config.runCommand (~/.config/yarn/global/node_modules/@oclif/config/lib/config.js:151:9)
    at async Main.run (~/.config/yarn/global/node_modules/@oclif/command/lib/main.js:21:9)
    at async Main._run (~/.config/yarn/global/node_modules/@oclif/command/lib/command.js:44:20)
```

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Install netlify-cli@2.26.0 or later
2. Run `netlify link`

**- What is the expected behavior?**

This works in 2.25.0.

```sh
> netlify link

netlify link will connect this folder to a site on Netlify

? How do you want to link this folder to a site? (Use arrow keys)
❯ Use current git remote origin (https://github.com/williamjacksn/accio)
  Search by full or partial site name
  Choose from a list of your recently updated sites
  Enter a site ID
```

**- Local Environment Information**

```sh
> netlify status --verbose
──────────────────────┐
 Current Netlify User │
──────────────────────┘
Name:  William Jackson
Email: william@subtlecoolness.com
Teams:
  William Jackson's team: Collaborator
 ›   Warning: Did you run `netlify link` yet?
 ›   Error: You don't appear to be in a folder that is linked to a site
```

**Comment by williamjacksn** [comment]
I believe this was introduced in https://github.com/netlify/cli/pull/635
